/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.2 */

#include "aap_protobuf/service/navigationstatus/message/NavigationState.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif


/* The following messages exceed 64kB in size: aap_protobuf_service_navigationstatus_message_NavigationState */

/* The PB_FIELD_32BIT compilation option must be defined to support messages that exceed 64 kB in size. */
#ifndef PB_FIELD_32BIT
#error Enable PB_FIELD_32BIT to support messages exceeding 64kB in size: aap_protobuf_service_navigationstatus_message_NavigationState
#endif
PB_BIND(aap_protobuf_service_navigationstatus_message_NavigationState, aap_protobuf_service_navigationstatus_message_NavigationState, 4)



